### ISSUE TITLE
import5eChar

### ISSUE THREAD

**Issue by oganm** [oganm/printSheetApp#1]
@chsims1. saw you forked this. If you are interested in making something like this, most of the code is actually in [oganm/import5eChar](https://github.com/oganm/import5eChar). This merely calls functions from there

**Comment by chsims1** [comment]
Cheers, looking for an easy way to do the conversion but obviously don't want to reinvent the wheel.On 11 Jun 2018 19:33, Burak Ogan Mancarci <notifications@github.com> wrote:@chsims1. saw you forked this. If you are interested in making something like this, most of the code is actually in oganm/import5eChar. This merely calls functions from there
