### ISSUE TITLE
Weapons not parsed properly

### ISSUE THREAD

**Issue by povk** [oganm/printSheetApp#3]
Weapons are not parsed and are jumbled into a single line when exporting.

See https://imgur.com/a/ZcHP2Ji

**Comment by povk** [comment]
The cause was improper formatting of ranged weapon distance on my character sheet. When I added range as two slash separated values it did generate properly.

**Comment by oganm** [comment]
What was written in there originally? I'd prefer to not fail in cases like that.

**Comment by oganm** [comment]
If you could attach the original sheet that was causing issues that'd be great
