### ISSUE TITLE
Expertise

### ISSUE THREAD

**Issue by Bloody-Nine** [oganm/printSheetApp#4]
So the sheet does not have a place to add Rogue's expertise, nor can the bot add expertise as far as I can tell.

**Comment by oganm** [comment]
the sheet does not have a visual indicator for expertise if you have a sheet that you like I that has the expertise I might be interested in it.

The modifiers however should be correct in both pdf sheet and the interactive sheet. At least they are in my test cases. If you have a character with expertise that doesn't work could you send the file to me?
